server:
  port: 9040

spring:
  application:
    name: "ServicioFacturacion"
    
  config:
    import: consul:localhost:8500   

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
