server:
  port: 9030

spring:

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:file:c:/h2/bbdd_cloud_calificaciones_productos_TOCOTO
    driverClassName: org.h2.Driver
    username: sa
    password: