server:
  port: 8888

logging.level.root: INFO

spring:
  application:
    name: "SpringCloudConfigServer"

  cloud:
    config:
      server:
        git: 
          uri: https://github.com/lrag/Patrones.git
          default-label: main
          clone-on-start: true
          
  security:
    user:
      name: root
      password: root
    
    