server:  
  port: 8080
  
spring:  
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #Para indicar que debe llamar al servicio de resgistro y descubrimiento para averguar cuantas aplicaciones hay
      
      default-filters:
      - name: FiltroCronometro      
      - name: FiltroLog
      - name: FiltroHeaders      

      routes:
        - id: ServicioClientes
          uri: lb://ServicioClientes
          predicates:
            - Path=/clientes/**
        - id: ServicioProductos
          uri: lb://ServicioProductos
          predicates:
            - Path=/productos/**
        - id: ServicioPedidos
          uri: lb://ServicioPedidos
          predicates:
            - Path=/pedidos/**
        - id: ServicioCalificacionesProductos
          uri: lb://ServicioCalificacionesProductos
          predicates:
            - Path=/calificaciones_productos/**

    consul:
      host: localhost
      port: 8500
    
      discovery:
        register: false
        registerHealthCheck: false
        
  
  
            
        
        
