spring:
  application:
    name: "ServicioCalificacionesProductos"

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      username: root
      password: root
      fail-fast: true

