server:
  port: 9030

spring:
  application:
    name: "ServicioCalificacionesProductos"

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      username: root
      password: root

    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    

    
    