spring:
  application:
    name: "ServicioProductos_CQRS_Query"

  mongodb:
    embedded:
      version: 3.5.5

kafka:
  direccion: localhost:9092
  topic:
    nombre: topic-productos-cqrs
    grupo: "consumer-productos"